//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolsa_Empleados
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOS_VACANTE
    {
        public int id { get; set; }
        public string Compañia { get; set; }
        public string Tipo { get; set; }
        public string Posicion { get; set; }
        public string Ubicacion { get; set; }
        public string Categoria { get; set; }
        public string Descripcion_Trabajo { get; set; }
        public string Como_Aplicar { get; set; }
        public string Email { get; set; }
    }
}
