//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolsa_Empleados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bolsa_de_EmpleadosEntities1 : DbContext
    {
        public Bolsa_de_EmpleadosEntities1()
            : base("name=Bolsa_de_EmpleadosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADORs { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public virtual DbSet<DATOS_VACANTE> DATOS_VACANTE { get; set; }
        public virtual DbSet<NUMERO_DE_PAGINACION> NUMERO_DE_PAGINACION { get; set; }
        public virtual DbSet<POSTER> POSTERs { get; set; }
    }
}
