//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bolsa_Empleados
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTER
    {
        public int id { get; set; }
        public string Correo_Poster { get; set; }
        public string Contraseña_Poster { get; set; }
        public string Nombre_de_Compañia { get; set; }
    }
}
